#!/bin/bash
# C4: free slowdown window with smooth, scenario-agnostic future proximity.
set -eo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
TAG=${1:?usage: c4_compare.sh <tag> <detour-coef> [executor]}
DETOUR=${2:?usage: c4_compare.sh <tag> <detour-coef> [executor]}
EXECUTOR=${3:-ms18_maskteam_origscale_c06_s0}

MS_SCEN=cross COORD_MODEL=c2 COORD_C2_MLP_BACKBONE=1 \
    COORD_C2_MLP_CONFLICT_FEATURES=0 \
    COORD_C2_DIRECT_WAYPOINTS=1 COORD_C2_DIRECT_SPEED_PROFILE=1 \
    COORD_C2_JOINT_POINT_SPEED=0 COORD_C2_SLOWDOWN_WINDOW=1 \
    COORD_C2_CONFLICT_WINDOW=0 COORD_C2_SLOWDOWN_WIDTH_MAX=0 \
    COORD_C2_SMOOTH_DEPTH=${COORD_C2_SMOOTH_DEPTH:-0} \
    COORD_C2_WAYPOINT_SMOOTHING_PASSES=8 \
    COORD_C2_WAYPOINT_DISTANCE_SCALING=1 \
    COORD_C2_STATE_ORDERED_TARGET_GAP=0 COORD_C2_FIXED_YIELD_SPEED=0 \
    COORD_C2_PATH_COLLISION_ONLY=0 COORD_C2_COLLISION_FOCUS_STEPS=8 \
    COORD_C2_COLLISION_TIME_UNCERTAINTY=0 \
    COORD_C2_PROXIMITY_COLLISION=1 COORD_C2_PROXIMITY_APPROACH_BETA=1 \
    COORD_C2_PROXIMITY_MARGIN=${COORD_C2_PROXIMITY_MARGIN:-0} \
    COORD_C2_MEASURED_EXECUTOR_TIMING=1 COORD_C2_RANDOM_PRIORITY=1 \
    COORD_C2_CONSISTENCY_COEF=1 \
    COORD_C2_FUTURE_COLLISION_COEF=${COORD_C2_FUTURE_COLLISION_COEF:-5} \
    COORD_C2_SPEED_SMOOTH_COEF=0 COORD_C2_UNNECESSARY_SLOW_COEF=0 \
    COORD_C2_SPEED_EFFICIENCY_COEF=0 \
    COORD_C2_EXTRA_DELAY_COEF=${COORD_C2_EXTRA_DELAY_COEF:-1} \
    COORD_C2_DETOUR_DELAY_COEF="$DETOUR" \
    COORD_C2_EXPLICIT_GAP_COEF=0 COORD_C2_EXPLICIT_ANCHOR_COEF=0 \
    COORD_C2_EXPLICIT_POST_COEF=0 COORD_C2_INITIAL_PLAN_WEIGHT=1 \
    COORD_C2_PATH_RESIDUAL_COEF=1 COORD_C2_PATH_SMOOTH_COEF=0 \
    COORD_ITERS=${COORD_ITERS:-2000} COORD_SAVE_EVERY=${COORD_SAVE_EVERY:-200} \
    COORD_ENVS=${COORD_ENVS:-64} \
    bash "$ROOT/scripts/coord/train_local.sh" "$TAG" "$EXECUTOR"
