#!/bin/bash
# C7: mechanism-agnostic joint coordination for both agents.
#
# Reuses the compact C5 joint (x, y, v) MLP, but removes the fixed-priority
# projection.  Both agents' predicted paths and speeds reach the frozen ms18
# executor.  Safety is learned from the general time-aligned proximity risk;
# equal speed-delay and detour-delay weights make their sum a weak total-time
# cost without prescribing whether the solution must slow down or detour.
set -eo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
TAG=${1:-c7_jointboth_s0}
EXECUTOR=${2:-ms18_maskteam_origscale_c06_s0}

MS_SCEN=${MS_SCEN:-cross} COORD_MODEL=c2 COORD_C2_MLP_BACKBONE=1 \
    COORD_C2_MLP_CONFLICT_FEATURES=0 \
    COORD_C2_DIRECT_WAYPOINTS=1 COORD_C2_DIRECT_SPEED_PROFILE=1 \
    COORD_C2_JOINT_POINT_SPEED=1 COORD_C2_PHYSICAL_SPEED_CAPS=1 \
    COORD_C2_SLOWDOWN_WINDOW=0 COORD_C2_CONFLICT_WINDOW=0 \
    COORD_C2_WAYPOINT_SMOOTHING_PASSES=8 \
    COORD_C2_WAYPOINT_DISTANCE_SCALING=1 \
    COORD_C2_STATE_ORDERED_TARGET_GAP=0 COORD_C2_FIXED_YIELD_SPEED=0 \
    COORD_C2_PATH_COLLISION_ONLY=0 COORD_C2_COLLISION_FOCUS_STEPS=8 \
    COORD_C2_COLLISION_TIME_UNCERTAINTY=0 \
    COORD_C2_PROXIMITY_COLLISION=1 COORD_C2_PROXIMITY_APPROACH_BETA=1 \
    COORD_C2_PROXIMITY_MARGIN=${COORD_C2_PROXIMITY_MARGIN:-0.25} \
    COORD_C2_MEASURED_EXECUTOR_TIMING=1 COORD_C2_RANDOM_PRIORITY=0 \
    COORD_C2_CONSISTENCY_COEF=0 \
    COORD_C2_FUTURE_COLLISION_COEF=${COORD_C2_FUTURE_COLLISION_COEF:-30} \
    COORD_C2_SPEED_SMOOTH_COEF=0 \
    COORD_C2_UNNECESSARY_SLOW_COEF=0 \
    COORD_C2_SPEED_EFFICIENCY_COEF=0 \
    COORD_C2_EXTRA_DELAY_COEF=${COORD_C2_TOTAL_DELAY_COEF:-0.2} \
    COORD_C2_DETOUR_DELAY_COEF=${COORD_C2_TOTAL_DELAY_COEF:-0.2} \
    COORD_C2_EXPLICIT_GAP_COEF=0 COORD_C2_EXPLICIT_ANCHOR_COEF=0 \
    COORD_C2_EXPLICIT_POST_COEF=0 COORD_C2_INITIAL_PLAN_WEIGHT=1 \
    COORD_C2_PATH_RESIDUAL_COEF=${COORD_C2_PATH_RESIDUAL_COEF:-0.1} \
    COORD_C2_PATH_SMOOTH_COEF=0 \
    COORD_ITERS=${COORD_ITERS:-2000} COORD_SAVE_EVERY=${COORD_SAVE_EVERY:-100} \
    COORD_ENVS=${COORD_ENVS:-64} \
    bash "$ROOT/scripts/coord/train_local.sh" "$TAG" "$EXECUTOR"
