#!/bin/bash
# Minimal post-placement experiment: learn only A1 retreat around Box1.
set -eo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)

export STACK_PLANNER_TASK_CLASS=HumanoidMAStackPlannerRetreatTrain
export STACK_PLANNER_RETREAT_ONLY=1
export STACK_PLANNER_FRESH_START=0
export STACK_PLANNER_ENVS=${STACK_PLANNER_ENVS:-1024}
export STACK_PLANNER_HORIZON=${STACK_PLANNER_HORIZON:-16}
export STACK_PLANNER_LOW_STEPS=${STACK_PLANNER_LOW_STEPS:-15}
export STACK_PLANNER_PPO_EPOCHS=${STACK_PLANNER_PPO_EPOCHS:-2}
export STACK_PLANNER_CANDIDATES=${STACK_PLANNER_CANDIDATES:-1}
export STACK_PLANNER_VISIT_PENALTY=0
export STACK_PLANNER_RETREAT_DELTA_SCALE=${STACK_PLANNER_RETREAT_DELTA_SCALE:-2.0}
export STACK_PLANNER_RETREAT_BOX_PENALTY=${STACK_PLANNER_RETREAT_BOX_PENALTY:-10.0}
export STACK_PLANNER_BOTTOM_DISTURBANCE_WEIGHT=${STACK_PLANNER_BOTTOM_DISTURBANCE_WEIGHT:-10.0}
export STACK_PLANNER_RETREAT_ENDPOINT_PENALTY=${STACK_PLANNER_RETREAT_ENDPOINT_PENALTY:-0.25}
export STACK_PLANNER_CONSISTENCY_COEF=${STACK_PLANNER_CONSISTENCY_COEF:-0.25}
export STACK_RETREAT_ONLY_CLEARANCE=${STACK_RETREAT_ONLY_CLEARANCE:-1.5}
export STACK_RETREAT_ONLY_A2_DISTANCE=${STACK_RETREAT_ONLY_A2_DISTANCE:-3.0}
export STACK_EPISODE_LENGTH=${STACK_EPISODE_LENGTH:-300}

exec bash "$ROOT/TokenHSI-coord/stack_planner/train.sh" "$@"
